import { describe, expect, it } from "vitest";
import { findRowDuplicates } from "../../src/utils/findDuplicates.ts";
import { Position } from "../../src/types/Sudoku.ts";
import type { Grid } from "../../src/types/Sudoku.ts";

describe("findRowDuplicates", () => {
  it("should return empty set for grid with no duplicates", () => {
    const grid: Grid = [
      [
        { value: 1, isInitial: true },
        { value: 2, isInitial: true },
        { value: 3, isInitial: true },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
      ],
      [
        { value: 4, isInitial: true },
        { value: 5, isInitial: true },
        { value: 6, isInitial: true },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
      ],
      [
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
      ],
      [
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
      ],
      [
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
      ],
      [
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
      ],
      [
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
      ],
      [
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
      ],
      [
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
      ],
    ];

    const result = findRowDuplicates(grid);
    expect(result.size).toBe(0);
  });

  it("should find duplicates in a single row", () => {
    const grid: Grid = [
      [
        { value: 1, isInitial: true },
        { value: 2, isInitial: true },
        { value: 1, isInitial: false }, // duplicate
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
      ],
      [
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
      ],
      [
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
      ],
      [
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
      ],
      [
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
      ],
      [
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
      ],
      [
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
      ],
      [
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
      ],
      [
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
      ],
    ];

    const result = findRowDuplicates(grid);
    expect(result.size).toBe(2);
    expect(result.has(Position({ row: 0, col: 0 }))).toBe(true);
    expect(result.has(Position({ row: 0, col: 2 }))).toBe(true);
  });

  it("should find duplicates in multiple rows", () => {
    const grid: Grid = [
      [
        { value: 1, isInitial: true },
        { value: 2, isInitial: true },
        { value: 1, isInitial: false }, // duplicate
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
      ],
      [
        { value: 5, isInitial: true },
        { value: 5, isInitial: false }, // duplicate
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
      ],
      [
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
      ],
      [
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
      ],
      [
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
      ],
      [
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
      ],
      [
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
      ],
      [
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
      ],
      [
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
      ],
    ];

    const result = findRowDuplicates(grid);
    expect(result.size).toBe(4);
    expect(result.has(Position({ row: 0, col: 0 }))).toBe(true);
    expect(result.has(Position({ row: 0, col: 2 }))).toBe(true);
    expect(result.has(Position({ row: 1, col: 0 }))).toBe(true);
    expect(result.has(Position({ row: 1, col: 1 }))).toBe(true);
  });

  it("should find all duplicates when value appears three times", () => {
    const grid: Grid = [
      [
        { value: 1, isInitial: true },
        { value: 1, isInitial: false }, // duplicate
        { value: 1, isInitial: false }, // duplicate
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
      ],
      [
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
      ],
      [
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
      ],
      [
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
      ],
      [
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
      ],
      [
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
      ],
      [
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
      ],
      [
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
      ],
      [
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
      ],
    ];

    const result = findRowDuplicates(grid);
    expect(result.size).toBe(3);
    expect(result.has(Position({ row: 0, col: 0 }))).toBe(true);
    expect(result.has(Position({ row: 0, col: 1 }))).toBe(true);
    expect(result.has(Position({ row: 0, col: 2 }))).toBe(true);
  });

  it("should ignore undefined values", () => {
    const grid: Grid = [
      [
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
      ],
      [
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
      ],
      [
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
      ],
      [
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
      ],
      [
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
      ],
      [
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
      ],
      [
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
      ],
      [
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
      ],
      [
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
        { value: undefined, isInitial: false },
      ],
    ];

    const result = findRowDuplicates(grid);
    expect(result.size).toBe(0);
  });
});
